FROM python:3.10-slim

RUN apt-get update && apt-get install -y \
    git \
    curl \
    python3-dev \
    libffi-dev \
    libssl-dev \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip
RUN pip install platformio
